const fs = require('fs');
const file = 'C:/github/vibe_wrangler/test/smoke.js';
let s = fs.readFileSync(file, 'utf8');
const crlf = s.includes('\r\n');
s = s.replace(/\r\n/g, '\n');

const needle = `  assert.equal(orRow.channel, 'api');
  assert.ok(orRow.costUsd > 0);`;
const extra = `  assert.equal(orRow.channel, 'api');
  assert.ok(orRow.costUsd > 0);
  const grokApiRow = usageMod.finishRow({ model: 'grok-4.6', input: 10, cached: 0, output: 2, costUsd: 0.01, costSource: 'cli' }, { harness: 'grok', provider: 'native' });
  assert.equal(grokApiRow.channel, 'api');`;
if (!s.includes(needle)) throw new Error('orRow asserts missing');
if (!s.includes('grokApiRow')) s = s.replace(needle, extra);

const oldT = `  const grokSub = harnesses.resolve('grok', 'native', 'grok-4.6');
  const grokEnv = { XAI_API_KEY: 'xai', GROK_API_KEY: 'g', PATH: '/bin' };
  grokSub.harness.env(grokEnv, grokSub.provider);
  assert.equal(grokEnv.XAI_API_KEY, undefined);
  assert.equal(grokEnv.GROK_API_KEY, undefined);
  const orKeep = { OPENROUTER_API_KEY: 'or', XAI_API_KEY: 'xai' };
  or.harness.env(orKeep, or.provider);
  assert.equal(orKeep.OPENROUTER_API_KEY, 'or', 'OpenRouter still uses its own key');
  ok('native Claude, Codex and Grok strip API keys so the subscription login is used');`;
const newT = `  const grokSub = harnesses.resolve('grok', 'native', 'grok-4.6');
  const grokEnv = { XAI_API_KEY: 'xai', GROK_API_KEY: 'g', PATH: '/bin' };
  grokSub.harness.env(grokEnv, grokSub.provider);
  assert.equal(grokEnv.XAI_API_KEY, 'xai', 'native Grok still needs the xAI API key');
  const orKeep = { OPENROUTER_API_KEY: 'or', XAI_API_KEY: 'xai' };
  or.harness.env(orKeep, or.provider);
  assert.equal(orKeep.OPENROUTER_API_KEY, 'or', 'OpenRouter still uses its own key');
  ok('native Claude and Codex strip API keys so the subscription login is used');`;
if (!s.includes(oldT)) throw new Error('smoke grok strip block missing');
s = s.replace(oldT, newT);
fs.writeFileSync(file, crlf ? s.replace(/\n/g, '\r\n') : s);
console.log('patched smoke.js');
